site_name: Argo CD Vault Plugin
repo_url: https://github.com/argoproj-labs/argocd-vault-plugin
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/_overrides
  palette:
    primary: black
  favicon: assets/favicon.png
  font:
    text: Work Sans
  logo: assets/logo.png

extra_javascript:
- assets/versions.js
extra_css:
- assets/versions.css

nav:
  - Overview: index.md
  - How it Works: howitworks.md
  - Installation: installation.md
  - Usage: usage.md
  - Backends: backends.md
  - Configuration: config.md
  - CLI Reference:
    - argocd-vault-plugin: cmd/avp.md
    - argocd-vault-plugin generate: cmd/generate.md
    - argocd-vault-plugin version: cmd/version.md
  - Upgrading:
     - v0.x to v1.x: 0x-1x.md
  - Compatibility: compatibility.md
  - Releases â§‰: https://github.com/argoproj-labs/argocd-vault-plugin/releases
